### ISSUE TITLE
[Candidate 1v1 Imminent Victory] Does map require name change to Natural Threats Winter?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#28]
**Describe the bug**
Does map require name change to Natural Threats Winter? Please refer to Relax for more information.

**Expected behavior**
Map has proper name.

**Comment by RisingZH** [comment]
Personally I like that it has a different name. I would expect the name 'winter' if it is purely the texture which has changed.

**Comment by xezon** [comment]
I also think Imminent Victory is ok name.

**Comment by ReLaX82** [comment]
I think it should carry the same name and add Winter behind.

**Comment by Jundiyy** [comment]
Oh I finally found out how to read comments and reply lol
If the map was the Natural Threats with small minute changes and only new textures added, I would go with a similar name but since I made this map myself, it's not Relax's map (yes it looks similar but has some quite obvious differences), so for this reason I made my own name for it.

**Comment by ReLaX82** [comment]
Having the exact same X and Y and also the lower areas from top to bottom with same openings appeals like more or less a copy.

Nevermind, oils are different and supplies.

Just leave the map name and add ZH v1 then.

**Comment by Jundiyy** [comment]
Correct, I made the map keeping yours as the base (since that is what was asked from me) but swapped the right and left sides around, also swapped the supplies/supply area at the top and bottom and some other small edits, the map was made for a winter tournament.
