### ISSUE TITLE
[Candidate 1v1 Snowy Drought ZH v5] Top supply piles have wider gap

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#484]
## Observed behavior

Top supply piles have wider gap.

## Expected behavior

Mirrored supply piles have about equal space around them.

## Screenshots

![shot_20231125_165053_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aed0923a-2964-477e-a5b3-c835273ffba4)

![shot_20231125_165103_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b25a44a7-409c-46e0-acfb-084a1df563e7)

**Comment by Jundiyy** [comment]
Looked into the map today, firstly using World Builder and this problem looked okay then tested in game and was fine as well. 
![shot_20231210_204345_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/1d8f973b-c7ae-4460-aa01-8b1fc9999ac3)
![shot_20231210_204352_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/ef0b6da9-a660-4db2-972a-b6aedffc3c5c)
![shot_20231210_204359_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/e38fe217-49d3-493d-b595-45f66355cc0c)

**Comment by xezon** [comment]
Did you use the version from this repository?

**Comment by Jundiyy** [comment]
You're right, I should have. I was under the impression that no work had been done on this map other than sounds, hence I used v4. Perhaps Dominator can confirm. I will still test on v5 but I'd rather know what was changed.

**Comment by Jundiyy** [comment]
Downloaded and tested on v5. Managed to get the Firebase in but felt a bit harder, I did look at the maps and they seemed the same, so maybe I was imagining it being harder. The difference is due to the 2 small mountains being a bit different in size.

![shot_20231211_215431_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/6db32d2d-8e4f-4c9c-adb8-8a5c36ef4ddd)
![shot_20231211_215438_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/01a55f43-7e1b-47d7-92f0-17bf76a4f55d)

![shot_20231211_215442_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/5f18bd5c-ef39-407c-93b6-267b9c5ebebe)

**Comment by xezon** [comment]
Judging by the images the terrain and piles look the same from one version to another.

What is the recommended action here, if any?

**Comment by Jundiyy** [comment]
[Snowy Drought ZH v5.zip](https://github.com/user-attachments/files/16046256/Snowy.Drought.ZH.v5.zip)
I made some small edits to the map, mainly mountain areas, tweaking some bad tiles or unequal impassable terrain, middle small mountains have had some tweaks, should be a lot easier to build the Fire Bases. Added some Tank Traps to the mountains.
