### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#506]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0.

## Expected behavior

Map uses houses with good fire port setups.

## Screenshots

![shot_20231126_130436_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c2ea8307-6c21-4ccc-9a6a-588dee4d61a6)

![shot_20231126_130447_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/38d08b1d-5290-4453-9c96-28317d99deb4)

![shot_20231126_130525_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8255fad-6a54-4764-8613-5f0ee0aaba38)

![shot_20231126_130535_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/28a51c46-e923-4464-a619-771b204559ac)

![shot_20231126_130621_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f6ce3da8-d6c0-4d3c-8729-d93920e2d150)

![shot_20231126_130638_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34ceb945-0b61-4e20-8e0a-5cd8a2c230c8)

![shot_20231126_130653_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6782da1e-f274-4207-9a8b-7404e8edd5ef)

**Comment by xezon** [comment]
Not a blocker bug because structures sit on flat terrain and appear to cause no detriment.

**Comment by DoMiNaToRuk2** [comment]
You need to write these issues in more easy to understand language - missing fire ports unit fires from 0,0,0 means nothing to me.

Since it's not a blocker and it's going to be difficult to replace all these buildings and fit them in the same spaces, I'm going to say we leave this one. The map is being played in a tournament right now and we had no complaints.

**Comment by xezon** [comment]
Good fire ports:

![shot_20231127_182345_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/871a3279-41ec-4458-b24f-12d1b5bf0d6e)

Bad fire ports:

![shot_20231127_182359_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4207c9df-682a-43fb-b979-0f5b77431efa)

We can close, but perhaps you can replace the bad houses with better houses, especially in the map center.

**Comment by DoMiNaToRuk2** [comment]
As you can see, there are props stacked nicely against this building that will be too timely to reposition them all after changing a building that won't be the same size.
It's not game breaking since players experience the same thing, especially with random reverse. Please close and we focus on other maps with bigger issues.
