### ISSUE TITLE
[Candidate 4v4 Aquatic Paradise ZH v4] Performance drops to 10 FPS and becomes unplayable when AI is moving units around the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#657]
## Observed behavior

Performance drops to 10 FPS and becomes unplayable when AI is moving units around the map.

## Expected behavior

AI performance is good. No major slow downs.

## Screenshots

![shot_20240204_110844_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b5147c66-95fd-4d21-b26e-45cf16024ab3)

**Comment by xezon** [comment]
I suspect the problem here is that units try to move to the center of the map, which is impassable?

**Comment by NoMerciBKK** [comment]
i do not know what causes this problem i re done all the pathways + zones still causes 10fps at 3:30min ingame maybe remove the map from beeing ranked than

**Comment by xezon** [comment]
This problem cannot be fixed. We will drop this map for now.

**Comment by Jundiyy** [comment]
[Aquatic Paradise ZH v4.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15395577/Aquatic.Paradise.ZH.v4.zip)
I haven't tested it, too many maps and became lazy but I didn't change the AI stuff.
However, since the bases are small and there isn't enough space for the AI attacks, I don't know if it will work properly. I could probably move some (AI) stuff around a bit more.

And don't map should be removed because of AI only. If there are FPS drops for multiplayer as well then it makes sense.

**Comment by NoMerciBKK** [comment]
> [Aquatic Paradise ZH v4.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15395577/Aquatic.Paradise.ZH.v4.zip) I haven't tested it, too many maps in my maps folder and became lazy. Since the bases are small, the AI may not work 100%. I could probably move some (AI) stuff around a bit more.
> 
> And don't think map should be removed because of AI only. If there are FPS drops for multiplayer as well then it makes sense.

in the german community is a lot of beginners who wanna play maps vs AI so AI should at least work without lags

**Comment by xezon** [comment]
Still suffers significant drops. Is no joy to play with AI.

![shot_20240522_191822_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a8e5ccc6-0aa0-4f7b-8d90-35ccc6598289)

**Comment by Jundiyy** [comment]
Is it better than before? I can tweak a few small things but it won't make a massive difference. 
Perhaps a bit more ground in the middle might help. I am suspecting there isn't enough base and travel space. 

And yes NoMerci, I do agree AI should work, however, I don't think a map should be unranked because of no AI. It should be 'highly recommended' to have AI.

**Comment by xezon** [comment]
It appeared to be a bit better perhaps. I have not seen drops to 12 FPS.

The main problem is that these are choppy frames, aka one long frame, then normal frames. Is likely caused by pathfinding. As far as I am aware AI has "Hunt" behaviour that pushed them to center of map. Since map center is impassable, perhaps that causes huge pathfinding cost.

**Comment by xezon** [comment]
FPS problem is not fixable. Map will be moved to back log.
